# Generated by Django 5.1.3 on 2024-11-22 10:36

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_alter_profile_team'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='initiatives',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='initiative_author', to='UserProfile.profile'),
        ),
        migrations.AddField(
            model_name='initiatives',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='initiatives',
            name='feature_image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.image_upload_file),
        ),
        migrations.AddField(
            model_name='initiatives',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='initiative_category', to='api.category'),
        ),
    ]
