# Generated by Django 5.1.3 on 2024-11-25 03:42

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_alter_profile_team'),
        ('api', '0002_category_initiatives_author_initiatives_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('introduction', models.TextField()),
                ('content', models.TextField()),
                ('conclusion', models.TextField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('feature_image', models.ImageField(blank=True, null=True, upload_to=api.models.image_upload_file)),
                ('sub_title', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='story_author', to='UserProfile.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
