# Generated by Django 5.1.3 on 2024-11-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_initiatives_options_alter_blog_conclusion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='organizationdetail',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='organization/logo/'),
        ),
    ]
