# Generated by Django 5.1.3 on 2024-11-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=155)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('project', models.CharField(help_text='Write your Project Name!', max_length=255)),
                ('proposal_document', models.FileField(upload_to='projects/proposal/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('project_year', models.IntegerField(default=2024, help_text='Enter the project year (e.g., 2024)')),
            ],
            options={
                'unique_together': {('email', 'project_year')},
            },
        ),
    ]
