# Generated by Django 5.1.3 on 2024-11-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='project_year',
            field=models.IntegerField(default=2024, help_text='Enter the project year (e.g., 2024)'),
        ),
    ]
