# Generated by Django 5.1.3 on 2024-11-28 04:12

import career.models
import ckeditor_uploader.fields
import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opening_date', models.DateTimeField(default=datetime.datetime(2024, 11, 28, 4, 12, 36, 10282, tzinfo=datetime.timezone.utc))),
                ('deadline', models.DateTimeField(default=datetime.datetime(2024, 12, 5, 4, 12, 36, 10282, tzinfo=datetime.timezone.utc))),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('position_name', models.CharField(max_length=255)),
                ('job_description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('job_requirements', ckeditor_uploader.fields.RichTextUploadingField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('_is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': '1. Vacancies',
            },
        ),
        migrations.CreateModel(
            name='JobLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_location', models.CharField(help_text='(E.g. On-Site, Remote, Hybrid)', max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(help_text='(E.g. Full Time, Part Time)', max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='PositionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_type', models.CharField(help_text='E.g. Internship, Entry Level, Mid Level, Senior Level', max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='CareerApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=115)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer Not To Say', 'Prefer Not To Say')], max_length=55, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('phone_number', models.BigIntegerField()),
                ('cv', models.FileField(upload_to=career.models.upload_to_cv)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apply_position', to='career.career')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': '2. Applications',
            },
        ),
        migrations.AddField(
            model_name='career',
            name='job_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='career.joblocation'),
        ),
        migrations.AddField(
            model_name='career',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='career.jobtype'),
        ),
        migrations.AddField(
            model_name='career',
            name='position_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='career.positiontype'),
        ),
    ]
