# Generated by Django 5.1.3 on 2024-11-28 04:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 5, 4, 13, 8, 403779, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='career',
            name='opening_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 28, 4, 13, 8, 403779, tzinfo=datetime.timezone.utc)),
        ),
    ]
