# Generated by Django 5.1.3 on 2024-11-25 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='career',
            old_name='is_active',
            new_name='_is_active',
        ),
        migrations.AlterField(
            model_name='career',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 25, 4, 56, 54, 193690, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='career',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 2, 4, 56, 54, 194688, tzinfo=datetime.timezone.utc)),
        ),
    ]
