# Generated by Django 5.1.3 on 2024-11-28 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_alter_career_deadline_alter_career_opening_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 5, 4, 46, 2, 762697, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='career',
            name='opening_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 28, 4, 46, 2, 762697, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='career',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='careerapply',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='careerapply',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer Not To Say', 'Prefer Not To Say')], max_length=55),
        ),
    ]
