# Generated by Django 5.1.3 on 2024-11-26 08:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0010_joblocation_jobtype_positiontype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 26, 8, 33, 8, 711815, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='career',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 3, 8, 33, 8, 711815, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='career',
            name='job_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='career.joblocation'),
        ),
        migrations.AlterField(
            model_name='career',
            name='job_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='career.jobtype'),
        ),
        migrations.AlterField(
            model_name='career',
            name='position_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='career.positiontype'),
        ),
    ]
