# Generated by Django 5.1.3 on 2024-11-26 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0011_alter_career_created_at_alter_career_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 26, 8, 33, 36, 92869, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='career',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 3, 8, 33, 36, 92869, tzinfo=datetime.timezone.utc)),
        ),
    ]
