# Generated by Django 5.1.3 on 2024-11-26 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0015_careerapply_date_of_birth_careerapply_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 26, 11, 42, 19, 56660, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='career',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 3, 11, 42, 19, 56660, tzinfo=datetime.timezone.utc)),
        ),
    ]
