# Generated by Django 5.1.3 on 2024-12-02 04:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.TextField()),
                ('icon1', models.FileField(upload_to='icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])])),
                ('title1', models.TextField()),
                ('abstract_description1', models.TextField()),
                ('icon2', models.FileField(upload_to='icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])])),
                ('title2', models.TextField()),
                ('abstract_description2', models.TextField()),
                ('icon3', models.FileField(upload_to='icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])])),
                ('title3', models.TextField()),
                ('abstract_description3', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Goals',
            },
        ),
        migrations.CreateModel(
            name='OrganizationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('logo', models.FileField(blank=True, null=True, upload_to='organization/logo/')),
                ('location', models.TextField()),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PioneeringProjectsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.TextField()),
                ('founded', models.IntegerField()),
                ('projects', models.IntegerField()),
                ('communities', models.CharField(max_length=10)),
                ('volunteers', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Pioneering Projects Details',
            },
        ),
        migrations.CreateModel(
            name='WhatIsHCG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_question', models.TextField()),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Introduction',
            },
        ),
    ]
