# Generated by Django 5.1.3 on 2024-11-26 11:22

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=155)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=555)),
                ('message', ckeditor_uploader.fields.RichTextUploadingField()),
                ('is_accepted', models.BooleanField(default=False)),
            ],
        ),
    ]
