# Generated by Django 5.1.3 on 2024-11-29 05:24

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=155)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=555)),
                ('message', ckeditor_uploader.fields.RichTextUploadingField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(default=datetime.datetime(2024, 11, 29, 11, 9, 25, 448245))),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ('-submitted_at',),
            },
        ),
    ]
