# Generated by Django 5.1.3 on 2024-12-02 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='is_accepted',
        ),
        migrations.AlterField(
            model_name='contact',
            name='submitted_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 2, 9, 22, 23, 771041)),
        ),
    ]
