# Generated by Django 5.1.3 on 2024-11-26 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='submitted_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 26, 17, 13, 43, 619372)),
        ),
    ]
