# Generated by Django 5.1.3 on 2024-11-26 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_submitted_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-submitted_at',), 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='submitted_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 26, 17, 26, 57, 404114)),
        ),
    ]
